# Generated by Django 3.0.4 on 2020-03-12 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('proyecto', models.CharField(max_length=100)),
                ('etapa', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('unidad', models.IntegerField()),
                ('cliente', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('finspeccion', models.DateTimeField()),
                ('frmunicipal', models.DateTimeField()),
                ('dias', models.IntegerField()),
                ('estado', models.CharField(max_length=100)),
            ],
        ),
    ]
