# Generated by Django 3.0.4 on 2020-03-12 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimiento',
            name='dias',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='estado',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='etapa',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='finspeccion',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='frmunicipal',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='proyecto',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='sector',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='unidad',
            field=models.IntegerField(null=True),
        ),
    ]
