# Generated by Django 3.0.4 on 2020-03-13 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_app', '0002_auto_20200312_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimiento',
            name='fvconstructor',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='finspeccion',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='frmunicipal',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='unidad',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
